name: Push Docker Image

on:
  workflow_call:
    inputs:
      tag-name:
        type: string
        description: 'The tag name to use for the image'
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          labels: org.opencontainers.image.source = https://github.com/${{ github.repository }}
          tags: ghcr.io/${{ github.repository }}:${{ inputs.tag-name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
